[bastion]
bastion-host ansible_host=197.5.133.92

[haproxy_nodes]
haproxy-master ansible_host=10.0.1.11 keepalived_role=MASTER keepalived_priority=101 peer_ip=10.0.1.12
haproxy-backup ansible_host=10.0.1.12 keepalived_role=BACKUP keepalived_priority=100 peer_ip=10.0.1.11

[squid_nodes]
squid-master ansible_host=10.0.2.11 keepalived_role=MASTER keepalived_priority=101 peer_ip=10.0.2.12
squid-backup ansible_host=10.0.2.12 keepalived_role=BACKUP keepalived_priority=100 peer_ip=10.0.2.11

[internal_nodes:children]
haproxy_nodes
squid_nodes

[internal_nodes:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ProxyJump=ubuntu@197.5.133.92'

[haproxy_nodes:vars]
network_interface=ens3
bastion_gateway=10.0.1.254
subnet_cidr=10.0.1.0/24

[squid_nodes:vars]
network_interface=ens3
bastion_gateway=10.0.2.254
subnet_cidr=10.0.2.0/24

[bastion:vars]
bastion_inbound_ip=10.0.1.254
bastion_outbound_ip=10.0.2.254
inbound_cidr=10.0.1.0/24
outbound_cidr=10.0.2.0/24

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/openstack_ansible.pem

haproxy_vip=10.0.1.100
squid_vip=10.0.2.100

inbound_cidr=10.0.1.0/24
outbound_cidr=10.0.2.0/24
