[haproxy_nodes]
haproxy-master ansible_host=10.0.1.11 keepalived_role=MASTER keepalived_priority=101 peer_ip=10.0.1.12
haproxy-backup ansible_host=10.0.1.12 keepalived_role=BACKUP keepalived_priority=100 peer_ip=10.0.1.11

[squid_nodes]
squid-master ansible_host=10.0.2.11 keepalived_role=MASTER keepalived_priority=101 peer_ip=10.0.2.12
squid-backup ansible_host=10.0.2.12 keepalived_role=BACKUP keepalived_priority=100 peer_ip=10.0.2.11

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/openstack_ansible.pem
haproxy_vip=10.0.1.100
squid_vip=10.0.2.100
network_interface=eth0
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ProxyJump=ubuntu@197.5.133.188'
